### ISSUE TITLE
Environment Variables do not seem to work

### ISSUE THREAD

**Issue by NotMyself** [auth0/serverless-webtasks#10]
### Via Serverless CLI

1. Create function with the following serverless.yml
  ```yml
service: 
  name: webtasks-nodejs

provider:
  name: webtasks

environment:
  FOO: 'BAR'

functions:
  main:
    handler: handler

plugins:
  - '@webtask/serverless-webtasks'
  ```
2. Update the function to consume the env var
  ```javascript
'use strict';

module.exports = (context, cb) => {
    const message = `${process.env.FOO}: Go Serverless & Webtasks! Your function executed successfully!`
    console.log(message);
    cb(null, { message });
}
  ```
3. Deploy the function `serverless deploy`
4. Invoke the function `serverless invoke -f main`

## Result

```json
{
    "statusCode": 200,
    "body": "{\"message\":\"undefined: Go Serverless & Webtasks! Your function executed successfully!\"}"
}
```

## Expected Result

```json
{
    "statusCode": 200,
    "body": "{\"message\":\"BAR: Go Serverless & Webtasks! Your function executed successfully!\"}"
}
```

**Comment by glennblock** [comment]
I just verified, they do work.

Use this yml

```yaml
service: 
  name: getting-started

provider:
  name: webtasks
  stage: prod

functions:
  hello:
    handler: handler.hello
    events:
      - schedule: cron(* * * * *)

plugins:
  - serverless-webtasks
```

and this handler

```javascript
'use strict';

module.exports = (context, cb) => {
    const message = `Executed at: ${new Date(Date.now()).toString()}`;
    console.log(message);
    console.log(`foo:${context.secrets.foo}`);
    cb();
}
```

Output

```
Executed at: Tue Sep 19 2017 17:34:00 GMT+0000 (UTC)
foo:bar
finished webtask request 1505842440494.331745 with HTTP 200 in 124ms
```
