### ISSUE TITLE
If I run `serverless deploy` after removing `events.schedule` the cron is not being removed

### ISSUE THREAD

**Issue by jcenturion** [auth0/serverless-webtasks#13]
# Steps

1. Create a new task

```
service: 
  name: webtasks-nodejs  # NOTE: update this with your service name

provider:
  name: webtasks

# you can define service wide environment variables here
environment:
  variable1: value1

functions:
  main:
    handler: handler
    events:
      - schedule: cron(1 * * * *)

plugins:
  - '@webtask/serverless-webtasks'
```

2. Run `serverless deploy`

3. Remove `events.schedule`

```
service: 
  name: webtasks-nodejs  # NOTE: update this with your service name

provider:
  name: webtasks

# you can define service wide environment variables here
environment:
  variable1: value1

functions:
  main:
    handler: handler

plugins:
  - '@webtask/serverless-webtasks'
```

4. Run `serverless deploy`

# Expected

Webtask cron should be removed.
