### ISSUE TITLE
"serverless remove" does not remove the Webtask CRON job for any events

### ISSUE THREAD

**Issue by glennblock** [auth0/serverless-webtasks#7]
### Via Serverless & Webtask CLIs

1. Create a function with the following serverless.yml
```yml
service: 
  name: webtasks-nodejs

provider:
  name: webtasks

functions:
  main:
    handler: handler
    events:
      - schedule: cron(1 * * * *)

plugins:
  - '@webtask/serverless-webtasks'
```
2. Deploy the function `serverless deploy`
3. Remove the function `serverless remove`
4. Using the wt-cli list webtasks `wt ls -p serverless`
5. Using the wt-cli list cron tasks `wt cron ls -p serverless`

## Result

Webtask is removed, but CRON task is left behind.

## Expected Result

Both Webtask and CRON task should be removed.
